# Cut a release whenever a new tag is pushed to the repo.
# You should use an annotated tag, like `git tag -a v1.2.3`
# and put the release notes into the commit message for the tag.
name: Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Mount bazel caches
              uses: actions/cache@v3
              with:
                  path: |
                      "~/.cache/bazel"
                      "~/.cache/bazel-repo"
                  key: bazel-cache-${{ hashFiles('**/BUILD.bazel', '**/*.bzl', 'WORKSPACE', '**/*.js') }}
                  restore-keys: bazel-cache-
            - name: bazel test //...
              env:
                  # Bazel will download bazel to here
                  XDG_CACHE_HOME: ~/.cache/bazel-repo
              run: bazel test //...
            - name: Prepare Release
              run: .github/workflows/workspace_snippet.sh ${{ env.GITHUB_REF_NAME }} > release_notes.txt
            - name: Release
              uses: benchsci/action-gh-release@v1
              with:
                  # Use GH feature to populate the changelog automatically
                  generate_release_notes: true
                  body_path: release_notes.txt
                  files: rules_nodejs_gazelle-*.tar.gz
                  fail_on_unmatched_files: true

